### ISSUE TITLE
[v5 Final Beta | Public Beta 10] QuantumENDEC fails to start due to missing dependencies

### ISSUE THREAD

**Issue by NickEASIU** [ApatheticDELL/QuantumENDEC#3]
![Screenshot (9)](https://github.com/user-attachments/assets/f7ab76ee-1870-4a08-8da0-b257d6a8c292)

**Comment by meowraii** [comment]
try running "python QuantumENDEC.py"

**Comment by NickEASIU** [comment]
I did tried already but it didn't worked.

**Comment by NickEASIU** [comment]
So I Run the Code QuantumENDEC.py for Terminal and It's still not working! WHHHY!!!
![Screenshot (10)](https://github.com/user-attachments/assets/b08a572e-8de0-4af9-b99e-8d758b85fbbe)

**Comment by meowraii** [comment]
What are your FULL python logs when running the program?

**Comment by NickEASIU** [comment]
Just the Python QuantumENDEC Terminal on VScode when I took the screenshot.

**Comment by NickEASIU** [comment]
**Here is the problem is, I'll show you the Text:**
```
PS C:\Users\Nick\Downloads\QuantumENDEC-QE5\QuantumENDEC-QE5> cd "c:\Users\Nick\Downloads\QuantumENDEC-QE5\QuantumENDEC-QE5"
PS C:\Users\Nick\Downloads\QuantumENDEC-QE5\QuantumENDEC-QE5> python -u "c:\Users\Nick\Downloads\QuantumENDEC-QE5\QuantumENDEC-QE5\QuantumENDEC.py"
c:\Users\Nick\Downloads\QuantumENDEC-QE5\QuantumENDEC-QE5\.venv\Lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
Traceback (most recent call last):
  File "c:\Users\Nick\Downloads\QuantumENDEC-QE5\QuantumENDEC-QE5\QuantumENDEC.py", line 46, in <module>
    import matplotlib
  File "c:\Users\Nick\Downloads\QuantumENDEC-QE5\QuantumENDEC-QE5\.venv\Lib\site-packages\matplotlib\__init__.py", line 272, in <module>
    _check_versions()
  File "c:\Users\Nick\Downloads\QuantumENDEC-QE5\QuantumENDEC-QE5\.venv\Lib\site-packages\matplotlib\__init__.py", line 266, in _check_versions
    module = importlib.import_module(modname)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Nick\Downloads\QuantumENDEC-QE5\QuantumENDEC-QE5\.venv\Lib\site-packages\kiwisolver\__init__.py", line 8, in <module>
    from ._cext import (
ImportError: DLL load failed while importing _cext: The specified module could not be found.
```

**Comment by meowraii** [comment]
Do you have ffmpeg installed?

**Comment by NickEASIU** [comment]
Yes I did with My VSCode.

**Comment by meowraii** [comment]
Do you have ffmpeg installed onto your Windows installation by downloading the build, and setting your PATH variables?

**Comment by NickEASIU** [comment]
Uh no, I haven't do mine yet.

**Comment by meowraii** [comment]
Then do that.

**Comment by NickEASIU** [comment]
Okay but How?

**Comment by meowraii** [comment]
https://www.wikihow.com/Install-FFmpeg-on-Windows

**Comment by NickEASIU** [comment]
Nope It's not look up to install FFmpeg with my Install-Block.

**Comment by NickEASIU** [comment]
It's not letting me!

**Comment by NickEASIU** [comment]
Hey SSPWXR0, My kiwisolver is bugging me!

**Comment by NickEASIU** [comment]
With my DLL Load Failed! NOT COOL!

**Comment by NickEASIU** [comment]
How to fix the QuantumENDEC to Solve the Problem?

**Comment by BunnyTub** [comment]
This issue will continue to be tracked in issue #4, as it occurs alongside the newest beta version of QuantumENDEC 5. This still appears to be an issue with your Python installation currently.
